keycloak:
  issuer-uri: http://localhost:8080/realms/nexus_test

server:
  port: 8082

spring:
  application:
    name: nexus-gateway
  cloud:
    gateway:
      httpclient:
        ssl:
          useInsecureTrustManager: true
      routes:
        - id: dgsia-gateway-api
          uri: http://localhost:8081
          predicates:
            - Path=/**
          filters:
          - AddResponseHeader=Content-Security-Policy, frame-ancestors 'self' http://localhost:8082
          - CustomHeaderFilter

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: nexus3
            client-secret: 6DNjOj8zpbTXh33sPKB6DgL76fWXRK8h
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          keycloak:
            issuer-uri: ${keycloak.issuer-uri}
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.issuer-uri}
          jwk-set-uri: ${keycloak.issuer-uri}/protocol/openid-connect/certs
          
gateway-api:
  cors:
    enabled: true
    allowedOrigin: http://localhost:8082
  authentication:
    enabled: true