services:
  nexus:
    image: sonatype/nexus3:3.22.0
    container_name: nexus
    ports:
      - "8081:8081"
    volumes:
    # nexus-data contiene la persistenza dei dati di nexus
    #  - "./docker-data/nexus_dir:/nexus-data"
    # keycloack.json contiene la configurazione di keycloak per il nexus ed è richiesto dal plugin.
      - "./docker-data/keycloak.json:/opt/sonatype/nexus/etc/keycloak.json"
      - "./docker-data/nexus3-keycloak-plugin-0.6.0-SNAPSHOT-bundle.kar:/opt/sonatype/nexus/deploy/nexus3-keycloak-plugin-0.6.0-SNAPSHOT-bundle.kar"
    #environment:
    #  imposta credenziali admin:admin
    # - NEXUS_SECURITY_RANDOMPASSWORD=false
    #  - NEXUS_SECURITY_INITIAL_PASSWORD=admin
    networks:
      - dockernet
    restart: always

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.1
    container_name: keycloak
    ports:
      - "8080:8080"
    volumes:
    # in dev-mode, l'intera configurazione di keycloak viene memorizzata in un database H2. Esportare questa folder garantisce la persistenza.
      - "./docker-data/keycloak:/opt/keycloak/data/h2"
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin 
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    networks:
      - dockernet
    command: ["start-dev", "--hostname", "http://keycloak:8080"]
  
networks:
  dockernet:
    driver: bridge
    external: true
    name: dockernet
